- name: Install apache2
  hosts: 172.31.41.50
  tasks:
   - name: Install apache2
     apt: 
      name: apache2
      state: present
      update_cache: yes
   - name: Copy the index file
     copy:
      name: index.html
      dest: /var/www/html/
   - name: restarting apache2
     service:
      name: apache2 
      state: restarted
...
       
